// We'll use v3 of protobuf in this guide

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: hash.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_hash_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_hash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_hash_proto_rawDescGZIP(), []int{1}
}

func (x *HashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_hash_proto protoreflect.FileDescriptor

const file_hash_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hash.proto\"\x1f\n" +
	"\vHashRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"\"\n" +
	"\fHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash2.\n" +
	"\x04Hash\x12&\n" +
	"\aGetHash\x12\f.HashRequest\x1a\r.HashResponseB\aZ\x05/grpcb\x06proto3"

var (
	file_hash_proto_rawDescOnce sync.Once
	file_hash_proto_rawDescData []byte
)

func file_hash_proto_rawDescGZIP() []byte {
	file_hash_proto_rawDescOnce.Do(func() {
		file_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hash_proto_rawDesc), len(file_hash_proto_rawDesc)))
	})
	return file_hash_proto_rawDescData
}

var file_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hash_proto_goTypes = []any{
	(*HashRequest)(nil),  // 0: HashRequest
	(*HashResponse)(nil), // 1: HashResponse
}
var file_hash_proto_depIdxs = []int32{
	0, // 0: Hash.GetHash:input_type -> HashRequest
	1, // 1: Hash.GetHash:output_type -> HashResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hash_proto_init() }
func file_hash_proto_init() {
	if File_hash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hash_proto_rawDesc), len(file_hash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hash_proto_goTypes,
		DependencyIndexes: file_hash_proto_depIdxs,
		MessageInfos:      file_hash_proto_msgTypes,
	}.Build()
	File_hash_proto = out.File
	file_hash_proto_goTypes = nil
	file_hash_proto_depIdxs = nil
}
