# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hash.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhash.proto\"\x1a\n\x0bHashRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1c\n\x0cHashResponse\x12\x0c\n\x04hash\x18\x01 \x01(\t2.\n\x04Hash\x12&\n\x07GetHash\x12\x0c.HashRequest\x1a\r.HashResponseB\x0f\n\x0borg.exampleP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013org.exampleP\001'
  _globals['_HASHREQUEST']._serialized_start=14
  _globals['_HASHREQUEST']._serialized_end=40
  _globals['_HASHRESPONSE']._serialized_start=42
  _globals['_HASHRESPONSE']._serialized_end=70
  _globals['_HASH']._serialized_start=72
  _globals['_HASH']._serialized_end=118
# @@protoc_insertion_point(module_scope)
